### ISSUE TITLE
Impossible to create a dev.to API token

### ISSUE THREAD

**Issue by ccoVeille** [Sneezry/vscode-devto#13]
Here is my account https://dev.to/ccoVeille

I followed the step, and I was redirected to https://dev.to/settings/account

but I cannot find a way to create a dev.to API token

What am I missing ?

Thanks

**Comment by Sneezry** [comment]
Visit https://dev.to/settings/extensions, click **Generate API Key** in **DEV Community API Keys** section.

![image](https://github.com/Sneezry/vscode-devto/assets/1621293/0aaeed4b-6c06-4d4f-bb9f-ed3948d9a1bf)

**Comment by ccoVeille** [comment]
Thanks, I managed to get a token. I will test the extension from now.
