### ISSUE TITLE
Draft article breaks the extension

### ISSUE THREAD

**Issue by ccoVeille** [Sneezry/vscode-devto#14]
I have a lot of pending articles.

There are ideas I started to work on.

Many have no text or tag yet, only a title.

I cannot use your extension because of that.

**Comment by ccoVeille** [comment]
Please note the issue can be related to one of my articles that is in draft.

I have draft article that are 2 years old, maybe the way the API replies could lead to that. I didn't look any further.

I can provide replicate steps if needed.

But I don't think validating the JSON is empty would be a problem, only the context, comment, or reason of why it occurs for me may be adapted

**Comment by Sneezry** [comment]
Hi @ccoVeille , could you provide the repo steps to create a draft without any content? I have tested on my side, however, I cannot create posts without any content:

![image](https://github.com/Sneezry/vscode-devto/assets/1621293/73602835-1c8a-452c-8502-d179c440f633)

**Comment by ccoVeille** [comment]
Welcome back, I hope you enjoyed your days off.

I think it's an old behavior, my draft articles are 2 years old.

Can you give me the exact API call that your application does ? I'll check with my API key.

I'm on my phone now.

Last time, I failed using VS Code Developer console to see the API calls in network.

**Comment by Sneezry** [comment]
The extension calls `https://dev.to/api/articles/me/all` to fetch all your posts, and pick the post with the selected id when you click the items in the tree view.

**Comment by ccoVeille** [comment]
I managed to replicate it easily

- go on dev.to
- click on "create a post"
- set a title
- click on save

Here is what a post look alike

https://dev.to/ccoveille/test-for-sneezry-2719-temp-slug-1154266?preview=41397753595c0126a4847960dc1e90c6bbcdf349d254be6269da788de0eedb790dbb9fa3bfb39d79f93e3b9c1ddb067b660eba98244e79cfd22956f9

**Comment by Sneezry** [comment]
I still cannot replicate this issue. Did I miss anything? I cannot find a text field to type the post title, instead, I can only set the title in the meta yaml section of the body part.

![image](https://github.com/Sneezry/vscode-devto/assets/1621293/0b16f4ae-5d18-47e2-8439-89261b6ebeac)

![image](https://github.com/Sneezry/vscode-devto/assets/1621293/d661a010-bb22-40ad-925b-00d3c053b01e)

**Comment by ccoVeille** [comment]
Fixed with #16, closing

**Comment by Sneezry** [comment]
I have released v0.0.14 with the fix, please upgrade the extension to verify if this issue has been resolved.

**Comment by ccoVeille** [comment]
It works !

Your fix is better than mine, as I can now see (maybe edit) the draft documents that have no content

**Comment by ccoVeille** [comment]
You might have to update this https://marketplace.visualstudio.com/items/sneezry.vscode-devto/changelog
